/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   host-rules-editor-item.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

export {HostRulesEditorItem};

declare namespace UiElements {

  /**
   * Editor rule item editor.
   *
   * Renders inputs to control host rules.
   */
  class HostRulesEditorItem extends PolymerElement {

    /**
     * From host declaration. It can contain a `*` wildchar.
     *
     * Example:
     * ```
     * http://api.domain.com/*\/endpoint/
     * ```
     */
    hostFrom: string|null|undefined;

    /**
     * To host declaration. It must be valid URI to where the request will be
     * redirected.
     */
    hostTo: string|null|undefined;

    /**
     * Determines if the option is enabled.
     *
     * Note, this property will inherit boolean `false` value from `paper-checkbox`
     * if not set.
     */
    enabled: boolean|null|undefined;

    /**
     * Comment for the entry
     */
    comment: string|null|undefined;

    /**
     * If set comment section is opened and textarea visible.
     */
    commentOpened: boolean|null|undefined;

    /**
     * If set it renders "narrow" view fow small screens
     */
    narrow: boolean|null|undefined;

    /**
     * Toggles the comment section.
     */
    toggleComment(): void;
    _requestRemove(): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "host-rules-editor-item": UiElements.HostRulesEditorItem;
  }
}
