/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   host-rules-editor-item.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../paper-input/paper-input.d.ts" />
/// <reference path="../paper-input/paper-textarea.d.ts" />
/// <reference path="../paper-checkbox/paper-checkbox.d.ts" />
/// <reference path="../iron-collapse/iron-collapse.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />

declare namespace UiElements {

  /**
   * Editor rule item editor.
   *
   * Renders inputs to control host rules.
   */
  class HostRulesEditorItem extends Polymer.Element {

    /**
     * From host declaration. It can contain a `*` wildchar.
     *
     * Example:
     * ```
     * http://api.domain.com/*\/endpoint/
     * ```
     */
    hostFrom: string|null|undefined;

    /**
     * To host declaration. It must be valid URI to where the request will be
     * redirected.
     */
    hostTo: string|null|undefined;

    /**
     * Determines if the option is enabled.
     *
     * Note, this property will inherit boolean `false` value from `paper-checkbox`
     * if not set.
     */
    enabled: boolean|null|undefined;

    /**
     * Comment for the entry
     */
    comment: string|null|undefined;

    /**
     * If set comment section is opened and textarea visible.
     */
    commentOpened: boolean|null|undefined;

    /**
     * If set it renders "narrow" view fow small screens
     */
    narrow: boolean|null|undefined;

    /**
     * Toggles the comment section.
     */
    toggleComment(): void;
    _requestRemove(): void;
  }
}

interface HTMLElementTagNameMap {
  "host-rules-editor-item": UiElements.HostRulesEditorItem;
}
