/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/HostRulesEditorItem.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html} from 'lit-element';

export {HostRulesEditorItem};

declare namespace UiElements {

  /**
   * Editor rule item editor.
   *
   * Renders inputs to control host rules.
   */
  class HostRulesEditorItem extends LitElement {

    /**
     * From host declaration. It can contain a `*` wildchar.
     *
     * Example:
     * ```
     * http://api.domain.com/*\/endpoint/
     * ```
     */
    from: string|null|undefined;

    /**
     * To host declaration. It must be valid URI to where the request will be
     * redirected.
     */
    to: string|null|undefined;

    /**
     * Determines if the option is enabled.
     *
     * Note, this property will inherit boolean `false` value from `paper-checkbox`
     * if not set.
     */
    enabled: boolean|null|undefined;

    /**
     * Comment for the entry
     */
    comment: string|null|undefined;

    /**
     * If set comment section is opened and textarea visible.
     */
    commentOpened: boolean|null|undefined;

    /**
     * If set it renders "narrow" view fow small screens
     */
    narrow: boolean|null|undefined;

    /**
     * Enables compatibility with Anypoint platform
     */
    compatibility: boolean|null|undefined;

    /**
     * Enables material desing outlined theme
     */
    outlined: boolean|null|undefined;
    constructor();
    render(): any;
    _inputsTemplate(): any;
    _actionsTemplate(): any;
    _commentTemplate(): any;

    /**
     * Toggles the comment section.
     */
    toggleComment(): void;
    _requestRemove(): void;
    _inputHandler(e: any): void;
    _enabledHandler(e: any): void;
    _notify(name: any, value: any): void;
  }
}
