/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/HostRulesTester.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html} from 'lit-element';

export {HostRulesTester};

declare namespace UiElements {

  /**
   * An element that tests user input agains provided host rules.
   *
   * The host rules is a model received from `host-rules-editor`. However,
   * it can be any object that contains `from` and `to` properties.
   *
   * It evaluates user entered URL against provided rules and displays the
   * result of the computation.
   */
  class HostRulesTester extends LitElement {

    /**
     * Provided by the user URL
     */
    url: string|null|undefined;

    /**
     * Evaludated result of parsing the URL against rules
     */
    _result: string|null|undefined;

    /**
     * List of rules to use to evaluate the URL
     */
    rules: any[]|null|undefined;

    /**
     * Enables compatibility with Anypoint platform
     */
    compatibility: boolean|null|undefined;

    /**
     * Enables material desing outlined theme
     */
    outlined: boolean|null|undefined;
    constructor();
    render(): any;
    _resultTemplate(): any;
    testUrl(): void;
    _evaluate(): any;
    _evaluateAgainst(url: any, rule: any): any;
    _createRuleRe(input: any): any;
    _keyDown(e: any): void;
    _inputHandler(e: any): void;
  }
}
